[package]
name = "number"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/number"
homepage = "https://github.com/hilbert-space/number"
description = "Number."
